<?php

namespace App\Repository;

/**
 * FeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthenticationTokenRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneActiveByToken($token, $userId)
    {
        return $this->createQueryBuilder("aut")
            ->where('aut.token = :token')
            ->andWhere('aut.user = :user')
            ->andWhere('aut.createdAt < :now AND :now < aut.expires')
            ->setParameter('user', $userId)
            ->setParameter('token', $token)
            ->setParameter('now', new \DateTime())
            ->getQuery()->getOneOrNullResult();

    }
}
