<?php

namespace App\Repository;

/**
 * FeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPostsQuery($page, $perPage)
    {
        return $this->createQueryBuilder('p')
            ->addOrderBy('p.createdAt', 'desc')
            ->setFirstResult(($page -1) * $perPage)
            ->setMaxResults($perPage)
            ->getQuery();
    }
}
